// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Bids = sequelize.define('bids', {
    timestamp: {
      type: DataTypes.BIGINT,
    },
    energyValue: {
      type: DataTypes.DOUBLE,
    },
    recValue: {
      type: DataTypes.DOUBLE,
      field: 'RECValue',
    },
    totalValue: {
      type: DataTypes.DOUBLE,
    },
    active: {
      type: DataTypes.BOOLEAN,
      defaultValue: true,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'Bids',
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Bids.associate = (models) => {
    Bids.belongsTo(models.rpPs, {
      foreignKey: {
        name: 'rppIdKey',
        field: 'RPPId',
      },
      as: 'rpp',
    });
    Bids.belongsTo(models.sellers, {
      foreignKey: {
        name: 'sellerIdKey',
        field: 'sellerId',
      },
      target: {
        name: 'sellerId',
      },
      as: 'seller',
    });
  };

  return Bids;
};
