// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const ReCs = sequelize.define('reCs', {
    state: {
      type: DataTypes.STRING,
    },
    recType: {
      type: DataTypes.STRING,
      field: 'RECType',
    },
    year: {
      type: DataTypes.STRING,
    },
    value: {
      type: DataTypes.DOUBLE,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'RECs',
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  ReCs.associate = (models) => {
    ReCs.hasMany(models.rpPs, {
      foreignKey: {
        name: 'recIdKey',
        field: 'RECId',
      },
      as: 'recRpPs',
    });
  };

  return ReCs;
};
