// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Sellers = sequelize.define('sellers', {
    companyName: {
      type: DataTypes.STRING,
    },
    address: {
      type: DataTypes.STRING,
    },
    contactName: {
      type: DataTypes.STRING,
    },
    title: {
      type: DataTypes.STRING,
    },
    phone: {
      type: DataTypes.STRING,
    },
    signetAccount: {
      type: DataTypes.STRING,
    },
    agreementType: {
      type: DataTypes.STRING,
    },
    plantPhotos: {
      type: DataTypes.ARRAY(DataTypes.STRING),
    },
    creditLimit: {
      type: DataTypes.INTEGER,
    },
    creditAvailable: {
      type: DataTypes.INTEGER,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'Sellers',
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Sellers.associate = (models) => {
    Sellers.belongsTo(models.users, {
      foreignKey: {
        name: 'userIdKey',
        field: 'userId',
      },
      target: {
        name: 'userId',
      },
      as: 'user',
    });
    Sellers.hasMany(models.rpPs, {
      foreignKey: {
        name: 'sellerIdKey',
        field: 'sellerId',
      },
      target: {
        name: 'userId',
      },
      as: 'sellerRpPs',
    });
    Sellers.hasMany(models.bids, {
      foreignKey: {
        name: 'sellerIdKey',
        field: 'sellerId',
      },
      target: {
        name: 'sellerId',
      },
      as: 'sellerBids',
    });
    Sellers.hasMany(models.transactions, {
      foreignKey: {
        name: 'toSellerIdKey',
        field: 'toSellerId',
      },
      target: {
        name: 'userId',
      },
      as: 'toSellerTransactions',
    });
  };

  return Sellers;
};
