// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Zones = sequelize.define('zones', {
    iso: {
      type: DataTypes.STRING,
      field: 'ISO',
    },
    state: {
      type: DataTypes.STRING,
    },
    edc: {
      type: DataTypes.STRING,
      field: 'EDC',
    },
    loadZone: {
      type: DataTypes.STRING,
    },
    icEdescription: {
      type: DataTypes.STRING,
      field: 'ICEdescription',
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'Zones',
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Zones.associate = (models) => {
    Zones.hasMany(models.rpPs, {
      foreignKey: {
        name: 'isOzoneIdKey',
        field: 'ISOzoneId',
      },
      as: 'isOzoneRpPs',
    });
  };

  return Zones;
};
